version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-service:
    build:
      context: ../backend/services/user-service
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ecommerce_db
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8081:8080"
    depends_on:
      - db
    command: ["./build-app/user_service"]

  product-service:
    build:
      context: ../backend/services/product-service
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ecommerce_db
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8082:8080"
    depends_on:
      - db
    command: ["./build-app/product_service"]

  order-service:
    build:
      context: ../backend/services/order-service
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ecommerce_db
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8083:8080"
    depends_on:
      - db
    command: ["./build-app/order_service"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - product-service
      - order-service
      - db

volumes:
  db_data:
